steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/aquaria-app/aquaria:main'
      - '.'
    id: 'build-production'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aquaria-app/aquaria:main']
    id: 'push-production'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'aquaria-app'
      - '--image'
      - 'gcr.io/aquaria-app/aquaria:main'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
    id: 'deploy-production'

options:
  logging: CLOUD_LOGGING_ONLY
