/**
 * Banco de conhecimento das 27 Nakshatras (mansões lunares védicas).
 * Cada entrada traz símbolo, deidade regente, mitologia resumida, temas kármicos
 * e qualidades práticas para uso editorial no Céu do Dia.
 * Fonte principal: astrologyayurveda.com + tradição védica clássica.
 */

export interface NakshatraKnowledge {
  name: string;
  symbol: string;
  deity: string;
  deityDescription: string;
  mythology: string;
  karmicThemes: string[];
  practicalQualities: string;
  element: string;
  gana: string;
  rulingPlanet: string;
  signRange: string;
  animal: string;
  direction: string;
  color: string;
  gemstone: string;
  syllables: string[];
}

export const NAKSHATRA_KNOWLEDGE: Record<string, NakshatraKnowledge> = {
  Ashwini: {
    name: "Ashwini",
    symbol: "Cabeça de cavalo",
    deity: "Ashwini Kumaras",
    deityDescription: "Os gêmeos celestes curadores, médicos dos deuses que restauram vitalidade e juventude",
    mythology: "Os Ashwini Kumaras buscaram o Madhu Vidya — o segredo da imortalidade — com Rishi Dadhichi, prometendo restaurar sua cabeça com a de um cavalo. Rejuvenesceram Chyavana Rishi, origem do tônico ayurvédico Chyawanprash. A mitologia de Ashwini fala de cura, restauração e a faísca inicial da vida.",
    karmicThemes: [
      "Iniciar movimento onde há estagnação — o dharma de Ashwini é curar e reanimar",
      "Ação instintiva guiada por inteligência divina em vez de excesso de raciocínio",
      "Pioneirismo: quem nasce sob Ashwini aprende a responder à vida com espontaneidade",
      "A relação com o pai e figuras de autoridade tende a ser formativa e complexa",
    ],
    practicalQualities: "Velocidade, iniciativa, cura, pioneirismo. Ashwini dota seus nativos de energia dinâmica para curar, inovar e agir rapidamente. A sombra é a impaciência e o impulso sem direção.",
    element: "Terra",
    gana: "Deva",
    rulingPlanet: "Ketu",
    signRange: "0°00'–13°20' Áries",
    animal: "Cavalo macho",
    direction: "Sul",
    color: "Vermelho-sangue",
    gemstone: "Olho de gato (vaidurya)",
    syllables: ["Chu", "Che", "Cho", "La"],
  },
  Bharani: {
    name: "Bharani",
    symbol: "Yoni (útero/vulva)",
    deity: "Yama",
    deityDescription: "O deus da morte, da justiça e da transformação — guardião dos registros kármicos",
    mythology: "Yama, filho do deus Sol Surya e de Sanjna, é o juiz celestial que governa o caminho das almas após a morte. Ele conhece cada ato, cada palavra, cada verdade negada ou abraçada. Bharani, sob sua influência, conecta-se profundamente a karma, justiça, memória e a evolução da alma. O corvo, ave simbólica de Bharani, é mensageiro dos pitris (ancestrais).",
    karmicThemes: [
      "Criação que emerge da destruição — Bharani transforma dor em sabedoria",
      "Relação com o tempo: atrasos, pressão e a sensação de estar 'fora de sincronia'",
      "Memória intensa e sentido de justiça — nunca esquece o que foi dito ou feito",
      "Temas tabus: sexualidade, morte, trauma ancestral — são áreas de exploração natural",
      "Conexão com ancestrais e rituais de passagem",
    ],
    practicalQualities: "Resistência, profundidade emocional, senso de justiça. Bharani carrega o poder de suportar o trabalho de parto da criação — nada vem fácil, mas tudo que nasce é verdadeiro e duradouro.",
    element: "Terra",
    gana: "Manushya",
    rulingPlanet: "Vênus",
    signRange: "13°20'–26°40' Áries",
    animal: "Elefante macho",
    direction: "Oeste",
    color: "Vermelho-sangue",
    gemstone: "Diamante",
    syllables: ["Li", "Lu", "Le", "Lo"],
  },
  Krittika: {
    name: "Krittika",
    symbol: "Lâmina ou chama",
    deity: "Agni",
    deityDescription: "O deus do fogo — purificação, clareza e a força que queima o que não é verdade",
    mythology: "Krittika está ligada ao nascimento de Kartikeya, o valente filho de Shiva e comandante do exército celestial. Agni, o deus do fogo, carregou a energia ígnea de Shiva e a entregou ao Ganges sagrado. Kartikeya foi nutrido pelas seis irmãs Krittika — as estrelas das Plêiades — que o alimentaram com amor maternal. Em gratidão, ele desenvolveu seis cabeças para receber de todas simultaneamente.",
    karmicThemes: [
      "O fogo sagrado que purifica: queimar narrativas antigas, crenças limitantes e apegos",
      "Liderança visionária — Krittika corta pela ilusão para revelar a verdade",
      "Ciclos de altos e baixos como o fogo que flama e se aquieta — resiliência na renovação",
      "A relação com a mãe é formativa: disciplina, inteligência emocional, conexão com a natureza",
    ],
    practicalQualities: "Clareza, precisão, coragem, purificação. Krittika é a lâmina que separa o verdadeiro do falso. Favorece cirurgias, decisões que exigem corte limpo, e qualquer trabalho de refinamento.",
    element: "Fogo/Terra",
    gana: "Rakshasa",
    rulingPlanet: "Sol",
    signRange: "26°40' Áries – 10°00' Touro",
    animal: "Cabra/carneiro",
    direction: "Norte",
    color: "Branco",
    gemstone: "Rubi",
    syllables: ["A", "Ee", "U", "Ae"],
  },
  Rohini: {
    name: "Rohini",
    symbol: "Carro ou carruagem",
    deity: "Prajapati (Brahma)",
    deityDescription: "O senhor da criação — a força generativa que dá forma à matéria e à beleza",
    mythology: "Rohini é a esposa favorita da Lua (Chandra), que a preferia entre todas as suas 27 esposas nakshatras. O ciúme das outras esposas levou Daksha (pai das nakshatras) a amaldiçoar Chandra com definhamento. Os deuses intercederam e a maldição foi modificada — daí as fases da Lua, minguando e crescendo. Rohini representa o ponto de máxima fertilidade e beleza da Lua.",
    karmicThemes: [
      "Magnetismo criativo — Rohini dá forma física aos desejos, é a nakshatra da materialização",
      "Fertilidade em todos os sentidos: criatividade, abundância, sensualidade, crescimento",
      "Risco de ciúme e possessividade — a beleza que atrai também pode prender",
      "O cultivo paciente: Rohini ensina que a beleza verdadeira nasce do cuidado contínuo",
    ],
    practicalQualities: "Beleza, fertilidade, magnetismo, criatividade. Rohini é a mais fértil e sensual das nakshatras — favorece artes, agricultura, negócios, decoração e tudo que envolve criação de beleza e conforto.",
    element: "Terra",
    gana: "Manushya",
    rulingPlanet: "Lua",
    signRange: "10°00'–23°20' Touro",
    animal: "Serpente macho",
    direction: "Leste",
    color: "Branco",
    gemstone: "Pérola",
    syllables: ["O", "Va", "Vi", "Vu"],
  },
  Mrigashira: {
    name: "Mrigashira",
    symbol: "Cabeça de cervo",
    deity: "Soma (Chandra)",
    deityDescription: "O deus da Lua — a essência da imortalidade, do néctar divino e da busca interior",
    mythology: "Mrigashira está associada à busca de Soma — o elixir da imortalidade. Quando o néctar foi roubado, os deuses saíram em sua busca, com a Lua liderando a perseguição. O cervo (mriga) representa a inquietação graciosa da mente que procura, fareja e nunca se satisfaz completamente — sempre em busca de algo mais profundo.",
    karmicThemes: [
      "A busca como modo de vida — Mrigashira nunca está satisfeita, sempre explora",
      "Curiosidade insaciável: pesquisa, viagem, aprendizado contínuo",
      "Natureza dual — a parte de Touro busca conforto e beleza; a de Gêmeos busca conhecimento e comunicação",
      "O desafio é transformar a busca infinita em profundidade real",
    ],
    practicalQualities: "Curiosidade, gentileza, exploração, pesquisa. Mrigashira é a estrela do buscador — favorece investigação, viagem, escrita, perfumaria, ervas e qualquer campo que exija descoberta contínua.",
    element: "Terra",
    gana: "Deva",
    rulingPlanet: "Marte",
    signRange: "23°20' Touro – 6°40' Gêmeos",
    animal: "Serpente fêmea",
    direction: "Sul",
    color: "Prata/branco-prateado",
    gemstone: "Coral vermelho",
    syllables: ["Ve", "Vo", "Ka", "Ki"],
  },
  Ardra: {
    name: "Ardra",
    symbol: "Lágrima",
    deity: "Rudra",
    deityDescription: "O deus das tempestades — a fúria da natureza que destrói para renovar",
    mythology: "Rudra, forma primitiva e selvagem de Shiva, governa as tempestades, o trovão e a dissolução. Ardra carrega a energia do caos criativo — o momento em que a estrutura antiga se desfaz para que algo mais verdadeiro possa nascer. A lágrima simboliza a catarse: o choro que limpa, a tempestade que purifica o ar.",
    karmicThemes: [
      "Sobrevivência e resiliência — Ardra prospera em ambientes que testam limites",
      "A tempestade emocional que leva à renovação — as emoções intensas são o portal de transformação",
      "Risco de destruição sem propósito — quando a energia não encontra canal, torna-se caos",
      "Ativismo e coragem de confrontar verdades desconfortáveis",
    ],
    practicalQualities: "Intensidade emocional, transformação, coragem, investigação. Ardra favorece desbravar o desconhecido — física, tecnologia, meteorologia, jornalismo investigativo e qualquer trabalho que confronte o status quo.",
    element: "Água",
    gana: "Manushya",
    rulingPlanet: "Rahu",
    signRange: "6°40'–20°00' Gêmeos",
    animal: "Cachorro fêmea",
    direction: "Oeste",
    color: "Verde",
    gemstone: "Gomedha (hessonita)",
    syllables: ["Ku", "Gha", "Nga", "Cha"],
  },
  Punarvasu: {
    name: "Punarvasu",
    symbol: "Arco e aljava",
    deity: "Aditi",
    deityDescription: "A mãe dos deuses — a expansão infinita, o retorno à origem e a segunda chance",
    mythology: "Aditi é a mãe primordial, a deusa da abundância e do infinito. Punarvasu carrega a promessa de que, após cada perda, há retorno; após cada partida, há reencontro. O arco e a aljava representam a capacidade de lançar-se ao mundo e voltar renovado — o arqueiro que sempre retorna ao lar, como Rama retornando do exílio.",
    karmicThemes: [
      "Renovação e retorno à origem — Punarvasu é a nakshatra das segundas chances",
      "Crescimento espiritual através da jornada — sair para poder voltar mais sábio",
      "Contentamento: a arte de encontrar abundância no que já existe",
      "O arco aponta para o alvo — a capacidade de direcionar energia com propósito",
    ],
    practicalQualities: "Renovação, otimismo, retorno, sabedoria. Punarvasu favorece recomeços, reconciliações, viagens de retorno e qualquer situação que peça uma segunda chance com mais sabedoria.",
    element: "Água",
    gana: "Deva",
    rulingPlanet: "Júpiter",
    signRange: "20°00' Gêmeos – 3°20' Câncer",
    animal: "Gata",
    direction: "Norte",
    color: "Chumbo/prateado",
    gemstone: "Safira amarela",
    syllables: ["Ke", "Ko", "Ha", "Hi"],
  },
  Pushya: {
    name: "Pushya",
    symbol: "Úbere de vaca ou lótus",
    deity: "Brihaspati",
    deityDescription: "O guru dos deuses — a sabedoria que nutre, protege e sustenta",
    mythology: "Brihaspati é o preceptor dos deuses, o sacerdote celestial que conhece todos os rituais e mantras. Pushya é considerada a nakshatra mais auspiciosa do zodíaco — a energia da nutrição suprema, como o úbere da vaca sagrada que alimenta sem reservas. É a estrela dos pais, dos cuidadores, dos que sustentam.",
    karmicThemes: [
      "Nutrição como vocação — Pushya sustenta, alimenta e protege",
      "Sabedoria adquirida através da compaixão e do serviço",
      "Risco de dar demais e se esvaziar — aprender a nutrir-se também",
      "Tradição, ritual e conhecimento ancestral como fonte de força",
    ],
    practicalQualities: "Nutrição, proteção, sabedoria, estabilidade. Pushya é considerada a mais auspiciosa — favorece início de empreendimentos, rituais, educação, alimentação e qualquer ato de cuidado e sustentação.",
    element: "Água",
    gana: "Deva",
    rulingPlanet: "Saturno",
    signRange: "3°20'–16°40' Câncer",
    animal: "Cabra macho",
    direction: "Leste",
    color: "Vermelho-alaranjado",
    gemstone: "Safira azul",
    syllables: ["Hu", "He", "Ho", "Da"],
  },
  Ashlesha: {
    name: "Ashlesha",
    symbol: "Serpente enroscada",
    deity: "Nagas (Serpentes)",
    deityDescription: "Os seres-serpente — guardiões dos mistérios, da kundalini e do conhecimento oculto",
    mythology: "Os Nagas são os seres serpentinos da mitologia védica — nem deuses nem demônios, mas guardiões das águas subterrâneas, dos tesouros escondidos e do conhecimento esotérico. Ashlesha é a energia da serpente que se enrosca — ela abraça, penetra e hipnotiza. É a nakshatra do poder sutil, do veneno que também cura, da intuição que vai ao submundo e retorna com sabedoria.",
    karmicThemes: [
      "Exploração dos reinos ocultos — Ashlesha não teme o que está escondido",
      "Poder sutil: a influência que opera por baixo, sem ser vista",
      "Risco de manipulação e veneno emocional — a mesma energia que cura pode ferir",
      "Kundalini e transformação profunda — a serpente que sobe pela coluna da consciência",
    ],
    practicalQualities: "Intuição, mistério, profundidade psicológica, poder oculto. Ashlesha favorece trabalhos que exigem penetração — psicologia, pesquisa oculta, venenos/remédios, estratégia e qualquer campo que lide com o subconsciente.",
    element: "Água",
    gana: "Rakshasa",
    rulingPlanet: "Mercúrio",
    signRange: "16°40'–30°00' Câncer",
    animal: "Gato macho",
    direction: "Sul",
    color: "Preto-avermelhado",
    gemstone: "Esmeralda",
    syllables: ["Di", "Du", "De", "Do"],
  },
  Magha: {
    name: "Magha",
    symbol: "Trono real",
    deity: "Pitris (Ancestrais)",
    deityDescription: "Os espíritos ancestrais — os que vieram antes e sustentam a linhagem",
    mythology: "Magha é governada pelos Pitris, os espíritos dos ancestrais que habitam o reino entre a vida e a morte. O trono representa a autoridade legítima — não conquistada pela força, mas recebida pela linhagem e pelo direito de nascença. Magha conecta o nativo às raízes familiares, às tradições e ao peso (e ao privilégio) de carregar uma história.",
    karmicThemes: [
      "Ancestralidade como fundamento — Magha honra quem veio antes",
      "Liderança e autoridade legítima — o trono é ocupado por direito, não por usurpação",
      "O desafio do ego: distinguir entre servir à linhagem e servir ao orgulho",
      "Rituais de passagem e reverência aos mortos como fonte de poder",
    ],
    practicalQualities: "Liderança, tradição, dignidade, conexão ancestral. Magha favorece posições de autoridade, cerimônias, trabalho com linhagens, rituais, política e tudo que envolve respeito e hierarquia.",
    element: "Água",
    gana: "Rakshasa",
    rulingPlanet: "Ketu",
    signRange: "0°00'–13°20' Leão",
    animal: "Rato macho",
    direction: "Oeste",
    color: "Marfim/creme",
    gemstone: "Olho de gato (vaidurya)",
    syllables: ["Ma", "Mi", "Mu", "Me"],
  },
  "Purva Phalguni": {
    name: "Purva Phalguni",
    symbol: "Rede ou leito (as pernas dianteiras da cama)",
    deity: "Bhaga",
    deityDescription: "O deus da fortuna e do prazer — aquele que distribui alegria, riqueza e amor",
    mythology: "Bhaga é o deus védico da fortuna, do casamento e do prazer. Purva Phalguni é a energia do descanso merecido após o trabalho — a rede onde o guerreiro relaxa, o leito onde o amor se celebra. É a nakshatra do prazer criativo, da alegria de viver e da generosidade que flui quando se está satisfeito.",
    karmicThemes: [
      "Prazer como direito divino — não como indulgência culposa, mas como celebração da vida",
      "Criatividade e auto-expressão — Purva Phalguni precisa criar beleza para se sentir viva",
      "Relacionamento e romance — o leito é também o altar do amor",
      "Risco de excesso e preguiça — quando o descanso vira estagnação",
    ],
    practicalQualities: "Prazer, criatividade, romance, generosidade. Purva Phalguni favorece artes, entretenimento, romance, luxo, decoração e celebrações — tudo que envolve beleza e alegria de viver.",
    element: "Água",
    gana: "Manushya",
    rulingPlanet: "Vênus",
    signRange: "13°20'–26°40' Leão",
    animal: "Rato fêmea",
    direction: "Norte",
    color: "Amarelo-claro",
    gemstone: "Diamante",
    syllables: ["Mo", "Ta", "Ti", "Tu"],
  },
  "Uttara Phalguni": {
    name: "Uttara Phalguni",
    symbol: "Leito (as pernas traseiras da cama)",
    deity: "Aryaman",
    deityDescription: "O deus dos contratos e da hospitalidade — guardião dos compromissos e do dharma",
    mythology: "Aryaman é o deus védico que preside sobre contratos, casamentos, hospitalidade e as regras da sociedade. Se Bhaga (de Purva Phalguni) é o prazer do amor, Aryaman é o compromisso do amor — a transformação da paixão em aliança duradoura. O leito traseiro representa a sustentação do que foi construído: o lar, a família, a comunidade.",
    karmicThemes: [
      "Compromisso e alianças — Uttara Phalguni transforma o prazer em responsabilidade",
      "Dharma através da parceria — a realização vem do serviço conjunto",
      "O poder da colaboração — nada grande se constrói sozinho",
      "Integridade nos acordos — a palavra dada é sagrada",
    ],
    practicalQualities: "Compromisso, parceria, dharma, liderança. Uttara Phalguni favorece casamentos, contratos, acordos, filantropia e tudo que exige confiabilidade e responsabilidade compartilhada.",
    element: "Fogo",
    gana: "Manushya",
    rulingPlanet: "Sol",
    signRange: "26°40' Leão – 10°00' Virgem",
    animal: "Vaca/touro",
    direction: "Leste",
    color: "Azul-brilhante",
    gemstone: "Rubi",
    syllables: ["Te", "To", "Pa", "Pi"],
  },
  Hasta: {
    name: "Hasta",
    symbol: "Mão ou punho",
    deity: "Savitar",
    deityDescription: "O deus sol que desperta — a luz que coloca tudo em movimento, a mão que manifesta",
    mythology: "Savitar é o aspecto do Sol que surge antes do amanhecer — a força que impulsiona a vida, que dá o primeiro movimento. Hasta é a nakshatra da mão: o instrumento que transforma pensamento em matéria, ideia em ação. Quem domina a mão domina a criação. Savitar é também o deus das mantras — a palavra que manifesta realidade.",
    karmicThemes: [
      "Manifestação através das mãos — Hasta cria, constrói, cura, escreve",
      "Habilidade prática — o talento de fazer com as próprias mãos",
      "Ritmo e timing — Savitar é o senhor do momento certo de agir",
      "Risco de querer controlar tudo — a mão que segura demais sufoca",
    ],
    practicalQualities: "Destreza, manifestação, habilidade prática, timing. Hasta favorece artesanato, cirurgia, escrita, cura pelas mãos, culinária, magia e qualquer trabalho manual que transforme o mundo.",
    element: "Fogo",
    gana: "Deva",
    rulingPlanet: "Lua",
    signRange: "10°00'–23°20' Virgem",
    animal: "Búfalo fêmea",
    direction: "Sul",
    color: "Verde",
    gemstone: "Pérola",
    syllables: ["Pu", "Sha", "Na", "Tha"],
  },
  Chitra: {
    name: "Chitra",
    symbol: "Pérola brilhante ou jóia",
    deity: "Vishvakarma (Tvashtar)",
    deityDescription: "O arquiteto celeste — o designer divino que cria a beleza e a forma do universo",
    mythology: "Vishvakarma é o arquiteto dos deuses — o designer que criou o trono de Indra, o disco de Vishnu, as cidades celestes. Chitra é a nakshatra da beleza e do design — a pérola que lapida-se a si mesma. A energia de Chitra busca criar algo tão belo que pareça divino. Marte, seu regente, dá a energia para executar essa visão com precisão.",
    karmicThemes: [
      "A busca pela beleza como caminho espiritual — Chitra vê o divino na forma",
      "Design, arquitetura e a criação de estruturas belas e funcionais",
      "Risco de superficialidade — a pérola pode ser brilhante por fora e vazia por dentro",
      "A perfeição como processo — lapidar-se continuamente",
    ],
    practicalQualities: "Beleza, design, criatividade visual, perfeccionismo. Chitra favorece arquitetura, moda, artes visuais, design de joias, fotografia e qualquer campo onde forma e função se encontram.",
    element: "Fogo",
    gana: "Rakshasa",
    rulingPlanet: "Marte",
    signRange: "23°20' Virgem – 6°40' Libra",
    animal: "Tigre fêmea",
    direction: "Oeste",
    color: "Preto",
    gemstone: "Coral vermelho",
    syllables: ["Pe", "Po", "Ra", "Ri"],
  },
  Swati: {
    name: "Swati",
    symbol: "Broto ou planta jovem ao vento",
    deity: "Vayu",
    deityDescription: "O deus do vento — a força invisível que move tudo, a liberdade que não pode ser contida",
    mythology: "Vayu é o deus do vento e do sopro vital (prana). Ele é o pai de Hanuman (o herói macaco do Ramayana) e de Bhima (o mais forte dos Pandavas). Swati é como o broto que dança ao vento — flexível, independente, livre. A independência é a essência de Swati: nenhuma raiz profunda, nenhuma âncora, apenas a capacidade de se mover com as correntes.",
    karmicThemes: [
      "Liberdade como necessidade vital — Swati sufoca quando contida",
      "Adaptabilidade — como o broto que se curva mas não quebra",
      "Independência como identidade — o preço da liberdade é a solidão",
      "Prana e respiração — a saúde de Swati está ligada ao sopro vital",
    ],
    practicalQualities: "Independência, flexibilidade, adaptabilidade, diplomacia. Swati favorece comércio, negociação, música, medicina e qualquer campo que exija movimento, flexibilidade e pensamento independente.",
    element: "Fogo",
    gana: "Deva",
    rulingPlanet: "Rahu",
    signRange: "6°40'–20°00' Libra",
    animal: "Búfalo macho",
    direction: "Norte",
    color: "Preto",
    gemstone: "Gomedha (hessonita)",
    syllables: ["Ru", "Re", "Ro", "Ta"],
  },
  Vishakha: {
    name: "Vishakha",
    symbol: "Arco triunfal ou folha de pote de madeira decorada",
    deity: "Indra-Agni",
    deityDescription: "Indra (rei dos deuses) e Agni (fogo) — a energia dupla do poder e da purificação",
    mythology: "Vishakha é a única nakshatra com duas deidades: Indra, o rei dos deuses (poder, vitória, ambição), e Agni, o deus do fogo (purificação, sacrifício, determinação). Juntos, representam a busca incansável pela vitória — o guerreiro que não desiste até alcançar seu objetivo. O arco triunfal marca a entrada na esfera da conquista.",
    karmicThemes: [
      "Ambição e determinação — Vishakha é a nakshatra da meta que não se abandona",
      "Dualidade: a tensão entre dois caminhos, dois desejos, dois mundos",
      "Vitória através da perseverança — o arco só se abre para quem atravessa",
      "Risco de obsessão e unilateralidade — quando a meta vira a única coisa que existe",
    ],
    practicalQualities: "Determinação, ambição, foco, conquista. Vishakha favorece competição, pesquisa, política, debates e qualquer campo que requeira foco total e vontade de vencer.",
    element: "Fogo",
    gana: "Rakshasa",
    rulingPlanet: "Júpiter",
    signRange: "20°00' Libra – 3°20' Escorpião",
    animal: "Tigre macho",
    direction: "Leste",
    color: "Dourado",
    gemstone: "Safira amarela",
    syllables: ["Ti", "Tu", "Te", "To"],
  },
  Anuradha: {
    name: "Anuradha",
    symbol: "Flor de lótus ou arco",
    deity: "Mitra",
    deityDescription: "O deus da amizade e dos contratos — aquele que une, harmoniza e protege os laços",
    mythology: "Mitra é o deus védico da amizade, dos acordos e da cooperação. Ele é frequentemente associado a Varuna (o deus das águas cósmicas) como os dois pilares que sustentam a ordem social e divina. Anuradha é a nakshatra da amizade que supera obstáculos — o lótus que floresce mesmo na lama de Escorpião. Saturno, seu regente, dá a perseverança necessária para cultivar laços duradouros.",
    karmicThemes: [
      "Amizade e devoção — Anuradha é a nakshatra do companheirismo leal",
      "Sucesso através da cooperação — a vitória é compartilhada, não individual",
      "O lótus na lama — a capacidade de florescer em ambientes difíceis",
      "Perseverança nos relacionamentos — Anuradha não desiste dos laços",
    ],
    practicalQualities: "Amizade, lealdade, devoção, cooperação. Anuradha favorece trabalho em equipe, diplomacia, pesquisa, viagens ao exterior e qualquer campo que exija construção de pontes e alianças duradouras.",
    element: "Fogo",
    gana: "Deva",
    rulingPlanet: "Saturno",
    signRange: "3°20'–16°40' Escorpião",
    animal: "Cervo/lebre fêmea",
    direction: "Sul",
    color: "Vermelho-amarronzado",
    gemstone: "Safira azul",
    syllables: ["Na", "Ni", "Nu", "Ne"],
  },
  Jyeshtha: {
    name: "Jyeshtha",
    symbol: "Brinco circular ou umbrela real",
    deity: "Indra",
    deityDescription: "O rei dos deuses — o poder soberano, a autoridade e a proteção do que é seu",
    mythology: "Indra é o rei dos deuses, o guerreiro que derrotou o dragão Vritra para liberar as águas do mundo. Jyeshtha é a nakshatra mais velha e mais poderosa — o ancião que carrega a responsabilidade de proteger todos os outros. O brinco circular e a umbrela real representam a soberania e a autoridade que não são pedidas, mas assumidas. Mercúrio, seu regente, dá a inteligência estratégica.",
    karmicThemes: [
      "Autoridade e senioridade — Jyeshtha é a mais velha e a mais responsável",
      "Proteção do que é seu — a soberania que guarda e defende",
      "O peso do poder — a posição mais alta é também a mais solitária",
      "Risco de arrogância e ciúme — quando a autoridade vira dominação",
    ],
    practicalQualities: "Autoridade, proteção, responsabilidade, estratégia. Jyeshtha favorece liderança, gestão, proteção de patrimônio, advocacia e qualquer posição que exija senioridade e comando.",
    element: "Ar",
    gana: "Rakshasa",
    rulingPlanet: "Mercúrio",
    signRange: "16°40'–30°00' Escorpião",
    animal: "Cervo/lebre macho",
    direction: "Oeste",
    color: "Creme",
    gemstone: "Esmeralda",
    syllables: ["No", "Ya", "Yi", "Yu"],
  },
  Mula: {
    name: "Mula",
    symbol: "Raízes amarradas ou raiz",
    deity: "Nirriti",
    deityDescription: "A deusa da destruição e da dissolução — a força que desfaz para que o essencial permaneça",
    mythology: "Nirriti é a deusa védica da destruição — não como mal, mas como a força necessária que desfaz o que já não serve. Mula é a raiz: aquilo que vai até o fundo, que confronta o essencial, que destrói a superfície para chegar à verdade. Ketu, seu regente, dissolve a matéria para revelar o espírito. Mula não teme o fundo — é lá que encontra o ouro.",
    karmicThemes: [
      "Destruição como portal para a verdade — Mula desfaz para reconstruir",
      "Busca pela raiz — Mula não se satisfaz com respostas superficiais",
      "Risco de autodestruição — quando a força dissolvente se volta contra si",
      "Reconstrução desde o zero — a capacidade de recomeçar do fundo",
    ],
    practicalQualities: "Investigação profunda, destruição construtiva, busca da verdade, renascimento. Mula favorece pesquisa, filosofia, medicina, terapia, mineração e qualquer campo que exija ir até a raiz das coisas.",
    element: "Ar",
    gana: "Rakshasa",
    rulingPlanet: "Ketu",
    signRange: "0°00'–13°20' Sagitário",
    animal: "Cachorro macho",
    direction: "Norte",
    color: "Amarelo-claro",
    gemstone: "Olho de gato (vaidurya)",
    syllables: ["Ye", "Yo", "Bha", "Bhi"],
  },
  "Purva Ashadha": {
    name: "Purva Ashadha",
    symbol: "Leque ou cesto de vime",
    deity: "Apas",
    deityDescription: "As águas cósmicas — a força da purificação, da renovação e da invencibilidade",
    mythology: "Apas são as águas divinas — a força primordial que purifica, nutre e sustenta toda a vida. Purva Ashadha é a nakshatra da invencibilidade: o leque que abana para refrescar, o vime que é trançado para criar algo novo do que já existe. Vênus, seu regente, traz beleza, magnetismo e a capacidade de purificar ambientes com sua presença.",
    karmicThemes: [
      "Invencibilidade — Purva Ashadha não aceita derrota, apenas renovação",
      "Purificação — a capacidade de limpar o que está contaminado, em si e nos outros",
      "A força da água — gentil na superfície, irresistível na profundidade",
      "Vaidade como armadura — quando a beleza se torna escudo em vez de expressão",
    ],
    practicalQualities: "Invencibilidade, purificação, magnetismo, declaração. Purva Ashadha favorece oratória, debates, escritas, artes cênicas e qualquer campo que exija convicção e poder de persuasão.",
    element: "Ar",
    gana: "Manushya",
    rulingPlanet: "Vênus",
    signRange: "13°20'–26°40' Sagitário",
    animal: "Macaco macho",
    direction: "Leste",
    color: "Prata",
    gemstone: "Diamante",
    syllables: ["Bhu", "Dha", "Pha", "Dha"],
  },
  "Uttara Ashadha": {
    name: "Uttara Ashadha",
    symbol: "Presa de elefante ou pequeno leito",
    deity: "Vishvedevas",
    deityDescription: "Os deuses universais — os dez princípios divinos que governam a ordem cósmica",
    mythology: "Os Vishvedevas são dez deuses universais que representam os princípios fundamentais do dharma: bondade, verdade, determinação, habilidade, tempo, desejo, firmeza, ancestralidade, claridade e previsão. Uttara Ashadha é a última das nakshatras solares — a energia da conquista final, da vitória que não pode ser contestada. A presa de elefante simboliza a força inabalável de concluir.",
    karmicThemes: [
      "Vitória inquestionável — Uttara Ashadha é a última palavra, a conquista definitiva",
      "Integridade como fundamento — a vitória só é verdadeira se for justa",
      "A responsabilidade do líder que conquista — usar o poder para sustentar, não para dominar",
      "Perseverança — a presa do elefante não solta o que agarra",
    ],
    practicalQualities: "Liderança, integridade, conquista definitiva, determinação. Uttara Ashadha favorece posições de autoridade, administração, construção de legados e qualquer empreendimento que exija compromisso absoluto com a verdade.",
    element: "Ar",
    gana: "Manushya",
    rulingPlanet: "Sol",
    signRange: "26°40' Sagitário – 10°00' Capricórnio",
    animal: "Mangusto macho",
    direction: "Sul",
    color: "Cobre",
    gemstone: "Rubi",
    syllables: ["Bhe", "Bho", "Ja", "Ji"],
  },
  Shravana: {
    name: "Shravana",
    symbol: "Orelha ou três pegadas",
    deity: "Vishnu",
    deityDescription: "O preservador — aquele que ouve, aprende e sustenta a ordem do universo",
    mythology: "Vishnu, o preservador, mediu o universo em três passos (Trivikrama): terra, céu e o espaço entre eles. Shravana é a nakshatra da escuta — a orelha que recebe o conhecimento, que ouve antes de falar. As três pegadas representam os passos da aprendizagem: ouvir, assimilar, transmitir. A Lua, seu regente, traz a receptividade necessária para absorver a sabedoria.",
    karmicThemes: [
      "Escuta profunda — Shravana ouve o que não é dito, o silêncio entre as palavras",
      "Aprendizado e transmissão de conhecimento — a sabedoria que passa de ouvido a ouvido",
      "A arte de ouvir antes de agir — a paciência de quem espera o momento certo",
      "Risco de absorver demais — quando a escuta vira sobrecarga",
    ],
    practicalQualities: "Escuta, aprendizado, comunicação, sabedoria. Shravana favorece educação, música, terapia de escuta, consultoria, escrita e qualquer campo que exija absorção e transmissão de conhecimento.",
    element: "Ar",
    gana: "Deva",
    rulingPlanet: "Lua",
    signRange: "10°00'–23°20' Capricórnio",
    animal: "Macaco fêmea",
    direction: "Oeste",
    color: "Azul-claro",
    gemstone: "Pérola",
    syllables: ["Khi", "Khu", "Khe", "Kho"],
  },
  Dhanishta: {
    name: "Dhanishta",
    symbol: "Tambor ou flauta",
    deity: "Vasus",
    deityDescription: "Os oito deuses da abundância — os portadores da riqueza, do ritmo e da prosperidade",
    mythology: "Os Vasus são oito deuses védicos que representam os elementos da abundância: terra, água, fogo, vento, céu, sol, lua e estrelas. Dhanishta é a nakshatra do tambor — o ritmo que sincroniza, a música que move, a cadência que dá forma à experiência. Marte, seu regente, dá a energia e a paixão para manter o ritmo mesmo nas dificuldades.",
    karmicThemes: [
      "Ritmo e cadência — Dhanishta vive pelo próprio compasso interno",
      "Prosperidade e abundância — os Vasus trazem riqueza em todas as formas",
      "Música, som e movimento — a harmonia que organiza o caos",
      "O tambor como chamado — a capacidade de reunir e mobilizar pessoas",
    ],
    practicalQualities: "Ritmo, prosperidade, música, liderança. Dhanishta favorece música, dança, esportes, finanças, medicina e qualquer campo que exija senso de ritmo, coordenação e capacidade de criar harmonia.",
    element: "Ar",
    gana: "Rakshasa",
    rulingPlanet: "Marte",
    signRange: "23°20' Capricórnio – 6°40' Aquário",
    animal: "Leão macho",
    direction: "Leste",
    color: "Prata",
    gemstone: "Coral vermelho",
    syllables: ["Ga", "Gi", "Gu", "Ge"],
  },
  Shatabhisha: {
    name: "Shatabhisha",
    symbol: "Círculo vazio ou cem estrelas",
    deity: "Varuna",
    deityDescription: "O deus das águas cósmicas e da ordem universal — o guardião do céu noturno e dos mistérios",
    mythology: "Varuna é o deus das águas cósmicas — o oceano primordial que envolve tudo. Ele é o guardião da Rita, a ordem cósmica, e conhece todos os segredos do céu e da terra. Shatabhisha significa 'cem curandeiros' — a nakshatra da cura através do conhecimento secreto, da ciência, da tecnologia que revela o invisível. O círculo vazio representa o vazio que contém tudo.",
    karmicThemes: [
      "Cura através do conhecimento — Shatabhisha descobre o que está oculto",
      "Segredos e mistérios — a capacidade de ver o que outros não veem",
      "Isolamento como escolha — o círculo vazio é o espaço onde a verdade emerge",
      "Risco de frieza e distanciamento — quando a observação vira alienação",
    ],
    practicalQualities: "Cura, pesquisa, tecnologia, conhecimento secreto. Shatabhisha favorece medicina, astronomia, criptografia, ciência da computação, astrologia e qualquer campo que revele verdades ocultas através do intelecto.",
    element: "Ar",
    gana: "Rakshasa",
    rulingPlanet: "Rahu",
    signRange: "6°40'–20°00' Aquário",
    animal: "Cavalo fêmea",
    direction: "Sul",
    color: "Azul-esverdeado",
    gemstone: "Gomedha (hessonita)",
    syllables: ["Go", "Sa", "Si", "Su"],
  },
  "Purva Bhadrapada": {
    name: "Purva Bhadrapada",
    symbol: "Espada ou homem de duas faces / parte frontal do leito",
    deity: "Aja Ekapada",
    deityDescription: "O unípede sem cabra — a forma primordial de Rudra, o deus do fogo cósmico",
    mythology: "Aja Ekapada é uma forma misteriosa de Rudra/Shiva — o ser que existe com uma só perna, representando a ponte entre dois mundos, a dualidade que contém os opostos. Purva Bhadrapada é a nakshatra da dualidade radical — o homem de duas faces que vê os dois lados. Júpiter, seu regente, traz sabedoria, mas também a capacidade de sustentar paradoxos.",
    karmicThemes: [
      "Dualidade — a capacidade de existir em dois mundos simultaneamente",
      "Intensidade e paixão — Purva Bhadrapada não conhece meio-termo",
      "Sabedoria através do paradoxo — a verdade que contém a contradição",
      "Risco de extremismo — quando a dualidade vira divisão interna",
    ],
    practicalQualities: "Intensidade, sabedoria paradoxal, visão dual, determinação. Purva Bhadrapada favorece filosofia, escrita, ativismo, pesquisa oculta e qualquer campo que exija a capacidade de sustentar complexidade e contradição.",
    element: "Éter",
    gana: "Manushya",
    rulingPlanet: "Júpiter",
    signRange: "20°00' Aquário – 3°20' Peixes",
    animal: "Leão macho",
    direction: "Oeste",
    color: "Prata",
    gemstone: "Safira amarela",
    syllables: ["Se", "So", "Da", "Di"],
  },
  "Uttara Bhadrapada": {
    name: "Uttara Bhadrapada",
    symbol: "Serpente das profundezas / parte traseira do leito",
    deity: "Ahir Budhnya",
    deityDescription: "A serpente do fundo — a sabedoria que habita as profundezas do oceano cósmico",
    mythology: "Ahir Budhnya é a serpente que habita o fundo do oceano primordial — o lugar onde as águas são mais profundas, mais escuras e mais sábias. Uttara Bhadrapada é a nakshatra da sabedoria profunda, da alma antiga que já viu tudo e permanece serena. Saturno, seu regente, traz a paciência e a maturidade de quem conhece o tempo. As profundezas não assustam — é lá que mora o conhecimento.",
    karmicThemes: [
      "Sabedoria profunda — Uttara Bhadrapada é a alma velha que permanece calma na tempestade",
      "Serenidade como força — a paz que não é ausência de luta, mas presença de fundamento",
      "Oratória e eloquência — a capacidade de falar com a autoridade de quem conhece",
      "Risco de estagnação — quando a profundidade vira inércia",
    ],
    practicalQualities: "Sabedoria, serenidade, eloquência, maturidade. Uttara Bhadrapada favorece ensino, oratória, direito, filosofia, pesquisa e qualquer campo que exija profundidade de pensamento e calma sob pressão.",
    element: "Éter",
    gana: "Manushya",
    rulingPlanet: "Saturno",
    signRange: "3°20'–16°40' Peixes",
    animal: "Vaca fêmea",
    direction: "Norte",
    color: "Azul-púrpura",
    gemstone: "Safira azul",
    syllables: ["Du", "Tha", "Jha", "Da"],
  },
  Revati: {
    name: "Revati",
    symbol: "Peixe ou tambor",
    deity: "Pushan",
    deityDescription: "O guia das almas — o pastor celeste que protege os viajantes e nutre o caminho",
    mythology: "Pushan é o deus védico que guia as almas — o pastor celestial que protege os rebanhos, os viajantes e os que cruzam o limiar entre mundos. Revati é a última nakshatra do zodíaco — o ponto de completude, a fronteira final antes de recomeçar. O peixe nada livre no oceano infinito, sem medo do fim, porque sabe que o fim é sempre um começo. Mercúrio, seu regente, dá a leveza e a adaptabilidade do viajante.",
    karmicThemes: [
      "Completude — Revati é o fim do ciclo e o portal para o novo",
      "Proteção na travessia — a guia que acompanha na jornada final",
      "Nutrição do caminho — a capacidade de cuidar dos outros durante transições",
      "Risco de dispersão — quando a liberdade infinita vira falta de direção",
    ],
    practicalQualities: "Completude, proteção, transição, nutrição. Revati favorece viagens, hospedagem, cuidado animal, trabalho com finais e passagens, música e qualquer campo que envolva acompanhamento e proteção de jornadas.",
    element: "Éter",
    gana: "Deva",
    rulingPlanet: "Mercúrio",
    signRange: "16°40'–30°00' Peixes",
    animal: "Elefante fêmea",
    direction: "Leste",
    color: "Marrom",
    gemstone: "Esmeralda",
    syllables: ["De", "Do", "Cha", "Chi"],
  },
};

/** Retorna o conhecimento de uma nakshatra pelo nome. */
export function getNakshatraKnowledge(name: string): NakshatraKnowledge | null {
  return NAKSHATRA_KNOWLEDGE[name] || null;
}
